/**
 * Static map of available hero images.
 * This is a plain TypeScript object — no filesystem access needed at build time.
 * Works reliably on all platforms including Vercel.
 *
 * To add a new image: add the slug key and the serving path value.
 */
/** Product slugs — these render in compact showcase mode */
export const productSlugs = new Set([
  'amazon-basics-10-cup-pitcher', 'amazon-basics-replacement-3pack', 'aquacrest-ukf8001-3pack',
  'bluevua-ro100ropot-lite-uv', 'bluevua-ro100ropot-uv', 'brita-elite-2pack',
  'brita-standard-3pack', 'brita-standard-4pack', 'brita-ultramax-27-cup-dispenser',
  'elkay-51300c-watersentry-plus', 'everydrop-filter-1-edr1rxd1', 'everydrop-filter-a-edrarxd1',
  'ge-rpwfe', 'ge-xwfe', 'grayl-geopress-24oz-water-purifier-bottle',
  'grayl-tap-water-filter', 'grayl-ultrapress-16-9oz-water-purifier-bottle',
  'hydroblu-clear-flow-bottle', 'hydroblu-go-flow-water-gravity-bag',
  'hydroblu-sidekick-2-stage-straw-filter', 'hydroblu-versa-flow-water-filter',
  'ispring-rcc7ak', 'katadyn-befree-1-0l-water-filter-bottle',
  'katadyn-hiker-pro-transparent-filter', 'katadyn-pocket-water-filter',
  'katadyn-vario-water-filter', 'lifesaver-liberty-bottle',
  'lifestraw-family-1-0-portable-gravity-powered-water-purifier',
  'lifestraw-flex-advanced-water-filter', 'lifestraw-go-series',
  'membrane-solutions-filter-straw-4pack', 'membrane-solutions-sediment-6pack',
  'msr-aquatabs-30pack', 'msr-autoflow-xl-gravity-filter', 'msr-guardian-purifier',
  'msr-miniworks-ex-microfilter', 'msr-thru-link-in-line-water-filter',
  'msr-trailshot-pocket-sized-water-filter', 'naturenova-filter-straw-3pack',
  'pentair-everpure-h1200', 'pentair-everpure-h300',
  'platypus-gravityworks-4-0l-water-filter-system', 'platypus-quickdraw-microfilter-system',
  'pur-pitcher-filter-4pack', 'samsung-haf-qin',
  'sawyer-products-mini-water-filtration-system', 'sawyer-select-series-s3',
  'sawyer-squeeze-water-filtration-system', 'survivor-filter-pro',
  'survivor-filter-pro-x-electric-pump', 'survivor-filter-pro-x-electric-water-filter',
  'survivor-filter-squeeze-kit', 'timain-filter-straw-2pack',
  'universal-5micron-sediment-filter', 'waterdrop-g3p600',
  'waterdrop-wd-pf01a-plus-3pack', 'zerowater-5stage-4pack', 'zerowater-5stage-6pack',
]);

export const heroImages: Record<string, string> = {
  // ── Product hero images ──
  'amazon-basics-10-cup-pitcher': '/assets/amazon-basics-10-cup-pitcher-hero.webp',
  'amazon-basics-replacement-3pack': '/assets/amazon-basics-replacement-3pack-hero.webp',
  'aquacrest-ukf8001-3pack': '/assets/aquacrest-ukf8001-3pack-hero.webp',
  'bluevua-ro100ropot-lite-uv': '/assets/bluevua-ro100ropot-lite-uv-hero.webp',
  'bluevua-ro100ropot-uv': '/assets/bluevua-ro100ropot-uv-hero.webp',
  'brita-elite-2pack': '/assets/brita-elite-2pack-hero.webp',
  'brita-standard-3pack': '/assets/brita-standard-3pack-hero.webp',
  'brita-standard-4pack': '/assets/brita-standard-4pack-hero.webp',
  'brita-ultramax-27-cup-dispenser': '/assets/brita-ultramax-27-cup-dispenser-hero.webp',
  'elkay-51300c-watersentry-plus': '/assets/elkay-51300c-watersentry-plus-hero.webp',
  'everydrop-filter-1-edr1rxd1': '/assets/everydrop-filter-1-edr1rxd1-hero.webp',
  'everydrop-filter-a-edrarxd1': '/assets/everydrop-filter-a-edrarxd1-hero.webp',
  'ge-rpwfe': '/assets/ge-rpwfe-hero.webp',
  'ge-xwfe': '/assets/ge-xwfe-hero.webp',
  'ispring-rcc7ak': '/assets/ispring-rcc7ak-hero.webp',
  'membrane-solutions-filter-straw-4pack': '/assets/membrane-solutions-filter-straw-4pack-hero.webp',
  'membrane-solutions-sediment-6pack': '/assets/membrane-solutions-sediment-6pack-hero.webp',
  'msr-aquatabs-30pack': '/assets/msr-aquatabs-30pack-hero.webp',
  'naturenova-filter-straw-3pack': '/assets/naturenova-filter-straw-3pack-hero.webp',
  'pentair-everpure-h1200': '/assets/pentair-everpure-h1200-hero.webp',
  'pentair-everpure-h300': '/assets/pentair-everpure-h300-hero.webp',
  'pur-pitcher-filter-4pack': '/assets/pur-pitcher-filter-4pack-hero.webp',
  'samsung-haf-qin': '/assets/samsung-haf-qin-hero.webp',
  'timain-filter-straw-2pack': '/assets/timain-filter-straw-2pack-hero.webp',
  'universal-5micron-sediment-filter': '/assets/universal-5micron-sediment-filter-hero.webp',
  'waterdrop-g3p600': '/assets/waterdrop-g3p600-hero.webp',
  'waterdrop-wd-pf01a-plus-3pack': '/assets/waterdrop-wd-pf01a-plus-3pack-hero.webp',
  'zerowater-5stage-4pack': '/assets/zerowater-5stage-4pack-hero.webp',
  'zerowater-5stage-6pack': '/assets/zerowater-5stage-6pack-hero.webp',

  // ── Legacy survival filter product heroes (29 products) ──
  'grayl-geopress-24oz-water-purifier-bottle': '/assets/grayl-geopress-24oz-water-purifier-bottle-hero.webp',
  'grayl-tap-water-filter': '/assets/grayl-tap-water-filter-hero.webp',
  'grayl-ultrapress-16-9oz-water-purifier-bottle': '/assets/grayl-ultrapress-16-9oz-water-purifier-bottle-hero.webp',
  'hydroblu-clear-flow-bottle': '/assets/hydroblu-clear-flow-bottle-hero.webp',
  'hydroblu-go-flow-water-gravity-bag': '/assets/hydroblu-go-flow-water-gravity-bag-hero.webp',
  'hydroblu-sidekick-2-stage-straw-filter': '/assets/hydroblu-sidekick-2-stage-straw-filter-hero.webp',
  'hydroblu-versa-flow-water-filter': '/assets/hydroblu-versa-flow-water-filter-hero.webp',
  'katadyn-befree-1-0l-water-filter-bottle': '/assets/katadyn-befree-1-0l-water-filter-bottle-hero.webp',
  'katadyn-hiker-pro-transparent-filter': '/assets/katadyn-hiker-pro-transparent-filter-hero.webp',
  'katadyn-pocket-water-filter': '/assets/katadyn-pocket-water-filter-hero.webp',
  'katadyn-vario-water-filter': '/assets/katadyn-vario-water-filter-hero.webp',
  'lifesaver-liberty-bottle': '/assets/lifesaver-liberty-bottle-hero.webp',
  'lifestraw-family-1-0-portable-gravity-powered-water-purifier': '/assets/lifestraw-family-1-0-portable-gravity-powered-water-purifier-hero.webp',
  'lifestraw-flex-advanced-water-filter': '/assets/lifestraw-flex-advanced-water-filter-hero.webp',
  'lifestraw-go-series': '/assets/lifestraw-go-series-hero.webp',
  'msr-autoflow-xl-gravity-filter': '/assets/msr-autoflow-xl-gravity-filter-hero.webp',
  'msr-guardian-purifier': '/assets/msr-guardian-purifier-hero.webp',
  'msr-miniworks-ex-microfilter': '/assets/msr-miniworks-ex-microfilter-hero.webp',
  'msr-thru-link-in-line-water-filter': '/assets/msr-thru-link-in-line-water-filter-hero.webp',
  'msr-trailshot-pocket-sized-water-filter': '/assets/msr-trailshot-pocket-sized-water-filter-hero.webp',
  'platypus-gravityworks-4-0l-water-filter-system': '/assets/platypus-gravityworks-4-0l-water-filter-system-hero.webp',
  'platypus-quickdraw-microfilter-system': '/assets/platypus-quickdraw-microfilter-system-hero.webp',
  'sawyer-products-mini-water-filtration-system': '/assets/sawyer-products-mini-water-filtration-system-hero.webp',
  'sawyer-select-series-s3': '/assets/sawyer-select-series-s3-hero.webp',
  'sawyer-squeeze-water-filtration-system': '/assets/sawyer-squeeze-water-filtration-system-hero.webp',
  'survivor-filter-pro': '/assets/survivor-filter-pro-hero.webp',
  'survivor-filter-pro-x-electric-pump': '/assets/survivor-filter-pro-x-electric-pump-hero.webp',
  'survivor-filter-pro-x-electric-water-filter': '/assets/survivor-filter-pro-x-electric-water-filter-hero.webp',
  'survivor-filter-squeeze-kit': '/assets/survivor-filter-squeeze-kit-hero.webp',

  // ── Editorial hero images ──
  'about': '/assets/about-hero.webp',
  'amazon-basics-vs-brita-standard': '/assets/amazon-basics-vs-brita-standard-hero.webp',
  'best-backpacking-water-filters': '/assets/best-backpacking-water-filters-hero.webp',
  'best-countertop-filters': '/assets/best-countertop-filters-hero.webp',
  'best-off-grid-water-filters': '/assets/best-off-grid-water-filters-hero.webp',
  'best-pump-filters': '/assets/best-pump-filters-hero.webp',
  'best-refrigerator-filters': '/assets/best-refrigerator-filters-hero.webp',
  'best-replacement-filters': '/assets/best-replacement-filters-hero.webp',
  'best-survival-filters': '/assets/best-survival-filters-hero.webp',
  'best-under-sink-filters': '/assets/best-under-sink-filters-hero.webp',
  'best-water-filters-under-50': '/assets/best-water-filters-under-50-hero.webp',
  'best-whole-house-filters': '/assets/best-whole-house-filters-hero.webp',
  'bluevua-ro100ropot-uv-vs-bluevua-ro100ropot-lite-uv': '/assets/bluevua-ro100ropot-uv-vs-bluevua-ro100ropot-lite-uv-hero.webp',
  'bluevua-ro100ropot-uv-vs-ispring-rcc7ak': '/assets/bluevua-ro100ropot-uv-vs-ispring-rcc7ak-hero.webp',
  'brita-elite-vs-zerowater': '/assets/brita-elite-vs-zerowater-hero.webp',
  'brita-standard-vs-brita-elite': '/assets/brita-standard-vs-brita-elite-hero.webp',
  'brita-standard-vs-pur': '/assets/brita-standard-vs-pur-hero.webp',
  'everydrop-filter-1-vs-ge-xwfe': '/assets/everydrop-filter-1-vs-ge-xwfe-hero.webp',
  'ge-xwfe-vs-ge-rpwfe': '/assets/ge-xwfe-vs-ge-rpwfe-hero.webp',
  'history-of-water-filtration': '/assets/history-of-water-filtration-hero.webp',
  'how-to-choose-water-filter': '/assets/how-to-choose-water-filter-hero.webp',
  'is-tap-water-safe': '/assets/is-tap-water-safe-hero.webp',
  'ispring-rcc7ak-vs-waterdrop-g3p600': '/assets/ispring-rcc7ak-vs-waterdrop-g3p600-hero.webp',
  'lead-in-drinking-water': '/assets/lead-in-drinking-water-hero.webp',
  'nsf-certifications-explained': '/assets/nsf-certifications-explained-hero.webp',
  'pentair-everpure-h1200-vs-pentair-everpure-h300': '/assets/pentair-everpure-h1200-vs-pentair-everpure-h300-hero.webp',
  'pfas-in-drinking-water': '/assets/pfas-in-drinking-water-hero.webp',
  'reverse-osmosis-vs-carbon-filters': '/assets/reverse-osmosis-vs-carbon-filters-hero.webp',
  'samsung-haf-qin-vs-everydrop-filter-a': '/assets/samsung-haf-qin-vs-everydrop-filter-a-hero.webp',
  'timain-vs-membrane-solutions-straw': '/assets/timain-vs-membrane-solutions-straw-hero.webp',
  'timain-vs-naturenova-straw': '/assets/timain-vs-naturenova-straw-hero.webp',
  'understanding-tds': '/assets/understanding-tds-hero.webp',
  'water-filter-cost-analysis': '/assets/water-filter-cost-analysis-hero.webp',
  'water-filter-maintenance': '/assets/water-filter-maintenance-hero.webp',
  'water-filter-mistakes': '/assets/water-filter-mistakes-hero.webp',
  'water-filter-sizing-guide': '/assets/water-filter-sizing-guide-hero.webp',
  'water-filter-types-explained': '/assets/water-filter-types-explained-hero.webp',
  'water-filters-for-apartments': '/assets/water-filters-for-apartments-hero.webp',
  'water-filters-for-baby': '/assets/water-filters-for-baby-hero.webp',
  'water-filters-for-camping': '/assets/water-filters-for-camping-hero.webp',
  'water-filters-for-emergencies': '/assets/water-filters-for-emergencies-hero.webp',
  'water-filters-for-hard-water': '/assets/water-filters-for-hard-water-hero.webp',
  'water-filters-for-hiking': '/assets/water-filters-for-hiking-hero.webp',
  'water-filters-for-off-grid': '/assets/water-filters-for-off-grid-hero.webp',
  'water-filters-for-rv': '/assets/water-filters-for-rv-hero.webp',
  'water-filters-for-travel': '/assets/water-filters-for-travel-hero.webp',
  'water-filters-for-well-water': '/assets/water-filters-for-well-water-hero.webp',
  'water-filtration-beginner-guide': '/assets/water-filtration-beginner-guide-hero.webp',
  'waterdrop-plus-vs-brita-elite': '/assets/waterdrop-plus-vs-brita-elite-hero.webp',
  'what-is-reverse-osmosis': '/assets/what-is-reverse-osmosis-hero.webp',
  'zerowater-vs-pur': '/assets/zerowater-vs-pur-hero.webp',
};
